### ISSUE TITLE
公共静态资源CDN

### ISSUE THREAD

**Issue by haibinml** [mrlihx/epay#1]
设置成本地之后支付宝当面付无法显示二维码
加载其资源如下
../assets/static/jquery/1.12.4/jquery.min.js

实际会访问
域名/pay/qrcode/assets/static/layer/3.1.1/layer.min.js
会显示404

**Comment by mrlihx** [comment]
好。

**Comment by haibinml** [comment]
> 好。

但是加上路径之后就不会了
域名/assets
之后就正常了

**Comment by haibinml** [comment]
> 好。

paypal插件提交金额之后直接就会变成美元
例如提交1元提交到paypal插件之后就会变成1美元
可以在通道中引入includes/common.php之后使用管理员输入的usdt汇率settle_usdt_rate
也可以直接api获取当前最新汇率

**Comment by mrlihx** [comment]
> > 好。
> 
> paypal插件提交金额之后直接就会变成美元
> 例如提交1元提交到paypal插件之后就会变成1美元
> 可以在通道中引入includes/common.php之后使用管理员输入的usdt汇率settle_usdt_rate
> 也可以直接api获取当前最新汇率

我没用paypal插件，这个仓库是按我自己使用需求修改的。

**Comment by haibinml** [comment]
> > > 好。
> > 
> > 
> > paypal插件提交金额之后直接就会变成美元
> > 例如提交1元提交到paypal插件之后就会变成1美元
> > 可以在通道中引入includes/common.php之后使用管理员输入的usdt汇率settle_usdt_rate
> > 也可以直接api获取当前最新汇率
> 
> 我没用paypal插件，这个仓库是按我自己使用需求修改的。

那好吧
